apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: demo-api-success-rate
  namespace: demo
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  args:
    - name: namespace
    - name: service
  metrics:
    - name: success-rate
      interval: 30s
      count: 3
      successCondition: result[0] >= 0.95
      failureLimit: 1
      provider:
        prometheus:
          address: http://kube-prometheus-stack-prometheus.monitoring.svc.cluster.local:9090
          query: |
            (
              sum(
                rate(
                  flask_http_request_total{
                    namespace="{{args.namespace}}",
                    service="{{args.service}}",
                    status!~"5.."
                  }[1m]
                )
              )
            )
            /
            clamp_min(
              sum(
                rate(
                  flask_http_request_total{
                    namespace="{{args.namespace}}",
                    service="{{args.service}}"
                  }[1m]
                )
              ),
              0.001
            )
